name: Build and Deploy Svelte App to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger workflow on push to the `main` branch

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Svelte App
        run: npm run build

      - name: Setup GitHub Pages
        uses: uses: actions/deploy-pages@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build  # Adjust this according to your Svelte app's build output directory
