name: Build and Deploy Svelte App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm install
      - name: Build Svelte App
        run: npm run build

      # Upload build artifacts
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: dist
      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          artifact_name: github-pages
          publish_dir: dist
